dist: trusty
sudo: false

before_install:
    - pip install conan

install:
    - conan config install https://vuo.org/sites/default/files/conan-macos.zip
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --confirm vuoutils/*
